# Generated by Django 2.2.12 on 2021-12-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20211208_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='upazilla',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
