# Generated by Django 2.2.12 on 2021-12-12 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_upazilla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='car',
        ),
        migrations.RemoveField(
            model_name='order',
            name='model',
        ),
    ]
