# Generated by Django 2.2.12 on 2021-12-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20211212_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='division',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
