# Generated by Django 2.2.12 on 2021-12-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20211212_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='division',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='upazilla',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
